apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-redis
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: '>=v1.0.6'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the Redis Helm chart with a minimal, stable interface.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-redis
    Crossplane configuration that wraps the Bitnami Redis Helm chart.
  repository: ghcr.io/hops-ops/helm-redis
  source: github.com/hops-ops/helm-redis
